export const ResponseDesc = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  INVALID_BODY: "INVALID_BODY",
  INVALID_PARAM: "INVALID_PARAM",
  INVALID_TOKEN: "INVALID_TOKEN",
  BAD_REQ: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
}

export const ERROR_MSG = {
  UNKNOWN: "UNKNOWN",
  NOT_FOUND: 'DATA NOT FOUND',
  UNAUTHORIZED: "UNAUTHORIZED",
  BANNED: 'USER ALREADY BANNED',
}

export const ResponseStatusCode = {
  SUCCESS: '00',
  FAILED: '99',
  INVALID_BODY: '03',
  UNKNOWN_ERROR: '04',
  UNAUTHORIZED: '01',
}